# https://stackoverflow.com/a/61574295
# Can forks be synced automatically in GitHub?

name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'thomasmerz'
          git config --global user.email 'thomasmerz@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/yubiuser/pihole_adlist_tool.git
          git fetch upstream

          git checkout master
          git merge --no-edit upstream/master
          git push origin master

          git checkout development
          git merge --no-edit upstream/development
          git push origin development

